export interface Tip {
  UUID: number;
  RaceID: string;
  formula: 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8;
  method: 1 | 2 | 3;
  banker: 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8;
  multi: 0 | 1;
  First: string;
  FirstComment: string;
  FirstName: string;
  Second: string;
  SecondName: string;
  SecondComment: string;
  Third: string;
  ThirdName: string;
  ThirdComment: string;
  comments: string;
  amount: number;
  confirmationFlag: number;
  tipOfTheDay: number;
  ok: string[];
  good: string[];
  sub: string;
  event: string;
  eventComments: {
    1: string;
    2: string;
    3: string;
    4: string;
    5: string;
    6: string;
    7: string;
    8: string;
    9: string;
    10: string;
    11: string;
    12: string;
    13: string;
    14: string;
    15: string;
    16: string;
    17: string;
    18: string;

    event: string;
  };
  tipMark: {
    1: string;
    2: string;
    3: string;
    4: string;
    5: string;
    6: string;
    7: string;
    8: string;
    9: string;
    10: string;
    11: string;
    12: string;
    13: string;
    14: string;
    15: string;
    16: string;
    17: string;
    18: string;
  };
  runnerNames: {
    1: string;
    2: string;
    3: string;
    4: string;
    5: string;
    6: string;
    7: string;
    8: string;
    9: string;
    10: string;
    11: string;
    12: string;
    13: string;
    14: string;
    15: string;
    16: string;
    17: string;
    18: string;
  };
  bet_ticket: boolean;
  value: number;
}
